export type Definition = readonly [word: string, definition: string];
export type Check = readonly [statement: string, answer: boolean];

export type LessonContent = {
  title: string;
  strapline: string;
  objectives: string[];
  definitions: Definition[];
  languageTitle: string;
  languageNotes: string[];
  readingTitle: string;
  summary: string;
  keyIdeas: string[];
  checks: Check[];
  sentences: string[];
  tips: string[];
};

export type ProjectContent = {
  title: string;
  strapline: string;
  overview: string;
  usefulLanguage: string[];
  steps: string[];
  finalProduct: string;
};

export const lessonContent: Record<string, LessonContent> = {
  u1l1: {
    title: "My Body",
    strapline: "Meet the amazing systems that keep your body working.",
    objectives: ["Name important body organs and systems.", "Explain what each body system does.", "Use the present simple to describe facts."],
    definitions: [
      ["digestive system", "the body system that changes food into energy and nutrients"],
      ["respiratory system", "the body system that helps us breathe"],
      ["skeleton", "all the bones that support and protect the body"],
      ["muscle", "body tissue that moves bones and body parts"],
      ["heart", "the organ that pumps blood around the body"],
      ["lungs", "the organs that take oxygen from the air"],
      ["stomach", "the organ where food is mixed and broken down"],
      ["blood", "the red liquid that carries oxygen and nutrients"],
      ["nutrients", "useful substances in food that help the body grow"],
      ["oxygen", "a gas in the air that our bodies need"],
    ],
    languageTitle: "Present simple for scientific facts",
    languageNotes: ["Use the base verb with I, you, we and they: We breathe through our noses.", "Add -s or -es with he, she and it: The heart pumps blood.", "Use does not or doesn't for negative facts."],
    readingTitle: "Three Important Body Systems",
    summary: "The digestive system processes food, the respiratory system brings oxygen into the body, and the skeleton and muscles support, protect and move us. These systems work together every day.",
    keyIdeas: ["Food travels to the stomach after we swallow it.", "Oxygen passes from the lungs into the blood.", "Bones protect organs and muscles help bones move."],
    checks: [["The heart pumps blood around the body.", true], ["We use our digestive system when we breathe.", false], ["The lungs help oxygen enter the blood.", true], ["Muscles are not connected to bones.", false], ["The skeleton protects important organs.", true], ["Food is changed into useful energy and nutrients.", true]],
    sentences: ["The heart pumps blood around the body.", "We breathe air through our noses.", "Food travels to the stomach after we swallow it.", "Our skeleton is made of bones.", "Muscles help us move.", "The lungs pass oxygen to the blood.", "Body systems work together every day."],
    tips: ["Breathe is a verb; breath is a noun.", "The plural of lung is lungs, but heart is usually singular when we mean the organ."],
  },
  u1l2: {
    title: "Our Senses",
    strapline: "Discover how sight, hearing, smell, taste and touch help us learn.",
    objectives: ["Match the five senses to body parts.", "Understand Braille and sign language.", "Use capital letters correctly."],
    definitions: [
      ["sight", "the ability to see with the eyes"], ["hearing", "the ability to hear with the ears"],
      ["smell", "the ability to notice scents with the nose"], ["taste", "the ability to notice flavours with the tongue"],
      ["touch", "the ability to feel through the skin"], ["tongue", "the part of the mouth used for tasting and speaking"],
      ["skin", "the outer covering of the body that can feel"], ["Braille", "a reading code made from raised dots"],
      ["sign language", "a complete language that uses hands, face and movement"], ["combination", "a group of things joined or used together"],
    ],
    languageTitle: "Capital letters",
    languageNotes: ["Begin every sentence with a capital letter.", "Use capitals for names, countries, languages and nationalities.", "Write Egypt, English, Arabic, Spanish and Louis Braille with capitals."],
    readingTitle: "Different Ways to Understand the World",
    summary: "Our senses collect information all day. People who cannot hear may communicate through sign language, while people who cannot see may read Braille by touching patterns of raised dots.",
    keyIdeas: ["Each sense is connected to a body part.", "Sign languages can be different around the world.", "Braille dots can represent letters, numbers and punctuation."],
    checks: [["We taste with our tongue.", true], ["Braille is read only with the eyes.", false], ["Sign language is a complete language.", true], ["We hear with our nose.", false], ["Names of countries begin with capital letters.", true], ["The word english should begin with a small letter.", false]],
    sentences: ["We use our eyes to see.", "Our ears help us hear.", "Braille uses combinations of raised dots.", "Sign language helps people communicate.", "Louis Braille invented the Braille code.", "Mariam speaks Arabic and English.", "Our senses collect information all day."],
    tips: ["Savory describes food that is salty or spicy rather than sweet.", "Blind and deaf describe conditions; always speak respectfully about people."],
  },
  u1l3: {
    title: "Language",
    strapline: "Talk about choices, routines and things you would like to do.",
    objectives: ["Use want to and would like to.", "Recognise regular and irregular present verbs.", "Read a family conversation for detail."],
    definitions: [
      ["tidy", "to make a place clean and organised"], ["lounge", "a comfortable room where a family sits together"],
      ["creative", "good at making or imagining new things"], ["disappointed", "sad because something did not happen as hoped"],
      ["choose", "to decide which thing you want"], ["weekend", "Saturday and Sunday or the days away from school"],
      ["activity", "something that a person does"], ["routine", "something done regularly in the same way"],
      ["would like", "a polite way to say what someone wants"], ["matter", "a problem or situation that needs attention"],
    ],
    languageTitle: "Want to, would like to and present routines",
    languageNotes: ["Use want to + base verb: I want to paint.", "Would like to is polite: I would like to draw.", "Use the present simple with frequency words: Adam always runs in the park."],
    readingTitle: "A Saturday Choice",
    summary: "Kareema wants to do something creative while Adam wants to play in the park. Their mother finds a fair solution: the family will tidy first, then the children can play and draw outdoors.",
    keyIdeas: ["Family members can want different things.", "A good solution can include everyone's ideas.", "Responsibilities come before free-time activities."],
    checks: [["Kareema wants to do something creative.", true], ["Adam wants to stay in the lounge all day.", false], ["The family needs to tidy before going out.", true], ["Would like to is followed by a past-tense verb.", false], ["Choose means decide between options.", true], ["Always can describe a repeated routine.", true]],
    sentences: ["Mom wants to tidy the lounge.", "Kareema would like to draw a picture.", "Adam wants to run in the park.", "The family tidies the lounge first.", "We choose an activity together.", "I always help at the weekend.", "A fair plan can make everyone happy."],
    tips: ["Do not say I want drawing; say I want to draw.", "Would like is more polite than want in requests."],
  },
  u1l4: {
    title: "Parasports",
    strapline: "Celebrate athletes, effort, inclusion and achievement.",
    objectives: ["Understand key parasports vocabulary.", "Find facts in short biographies.", "Speak respectfully about ability and disability."],
    definitions: [
      ["parasport", "a sport adapted for athletes with disabilities"], ["athlete", "a person who trains and competes in sport"],
      ["champion", "a person who wins an important competition"], ["disability", "a condition that may affect movement, senses or activities"],
      ["medal", "a prize made of metal for a sporting achievement"], ["competition", "an event in which people try to win"],
      ["race", "a competition to see who is fastest"], ["international", "involving more than one country"],
      ["Paralympic Games", "an international sports event for athletes with disabilities"], ["team", "a group of people who work or compete together"],
    ],
    languageTitle: "Talking about achievements",
    languageNotes: ["Use who to add information about a person: Aya is a swimmer who won medals.", "Use has or have with won to connect past success to the present.", "Use respectful, person-first language when appropriate."],
    readingTitle: "Egyptian Parasport Champions",
    summary: "The Paralympic Games bring athletes with disabilities together from around the world. Egyptian swimmers and runners have competed internationally and won important medals through talent, training and determination.",
    keyIdeas: ["The Paralympic Games take place every four years.", "Parasports include many different events.", "Champions succeed through practice and courage."],
    checks: [["The Paralympic Games are an international competition.", true], ["Parasports are only swimming events.", false], ["A medal can be gold, silver or bronze.", true], ["Athletes never need to train.", false], ["A champion has achieved an important win.", true], ["Inclusive sport gives more people a chance to compete.", true]],
    sentences: ["The Paralympic Games take place every four years.", "Egypt has many talented parasport athletes.", "A champion trains with determination.", "The runner competes in several races.", "Athletes can win gold, silver or bronze medals.", "Inclusive sport welcomes different abilities.", "We celebrate effort as well as victory."],
    tips: ["Use athlete for a person; athletics is the group of track and field sports.", "Won is the past form and past participle of win."],
  },
  u1l5: {
    title: "Writing Paragraphs",
    strapline: "Choose strong titles and build clear healthy-living paragraphs.",
    objectives: ["Choose a title that matches a paragraph.", "Identify main and supporting ideas.", "Plan and write a short healthy-living paragraph."],
    definitions: [
      ["paragraph", "a group of sentences about one main idea"], ["title", "a short name that tells what a text is about"],
      ["summarise", "to give the main idea in a few words"], ["routine", "a regular way of doing something"],
      ["healthy", "good for the body or mind"], ["unhealthy", "not good for the body or mind"],
      ["habit", "something a person does often"], ["vitamin", "a substance in food that helps the body stay healthy"],
      ["mineral", "a natural substance the body needs in small amounts"], ["range", "a number of different types or choices"],
    ],
    languageTitle: "A clear paragraph",
    languageNotes: ["Start with a topic sentence that introduces the main idea.", "Add supporting details and examples.", "Choose a short title that summarises the whole paragraph."],
    readingTitle: "Healthy Choices",
    summary: "Short paragraphs explain how exercise, balanced food and active habits support a healthy life. Each paragraph needs a title that captures its main idea without adding unnecessary detail.",
    keyIdeas: ["Exercise is easier when it is enjoyable.", "A balanced diet includes different kinds of food.", "Long periods of sitting should be balanced with activity."],
    checks: [["A paragraph should focus on one main idea.", true], ["A title should include every detail in the text.", false], ["Fruit and vegetables can be healthy choices.", true], ["A topic sentence introduces the main idea.", true], ["Supporting sentences are never needed.", false], ["A good title can be interesting and clear.", true]],
    sentences: ["Exercise is important for a healthy body.", "Choose an activity that you enjoy.", "A balanced diet includes many kinds of food.", "Fruit and vegetables provide useful vitamins.", "Healthy habits grow through regular practice.", "A clear title shows the main idea.", "Supporting details make a paragraph stronger."],
    tips: ["The title is not usually a complete sentence.", "Use a capital letter for the important words in a title style, or follow your teacher's chosen style."],
  },
  u2l1: {
    title: "Vertebrates",
    strapline: "Classify animals with backbones into five important groups.",
    objectives: ["Define vertebrate and backbone.", "Compare mammals, reptiles, amphibians, fish and birds.", "Describe animal features and habitats."],
    definitions: [
      ["vertebrate", "an animal with a backbone"], ["backbone", "the line of connected bones along the back"],
      ["mammal", "a warm-blooded vertebrate with hair or fur"], ["reptile", "a cold-blooded vertebrate with scales"],
      ["amphibian", "a vertebrate that can live on land and in water"], ["fish", "a water vertebrate that breathes through gills"],
      ["bird", "a warm-blooded vertebrate with feathers and wings"], ["scales", "small hard plates that cover some animals"],
      ["gills", "body parts that take oxygen from water"], ["beak", "the hard mouth part of a bird"],
    ],
    languageTitle: "Describing and classifying animals",
    languageNotes: ["Use have or has for features: Birds have feathers.", "Use can and cannot for abilities: Most birds can fly.", "Use such as to introduce examples."],
    readingTitle: "The Five Vertebrate Groups",
    summary: "Vertebrates include mammals, reptiles, amphibians, fish and birds. Scientists classify them by features such as body covering, temperature, habitat, breathing and the way their young are born.",
    keyIdeas: ["Mammals usually give birth to live young.", "Fish use gills to take oxygen from water.", "Birds have feathers, wings and beaks."],
    checks: [["Vertebrates have backbones.", true], ["All mammals lay eggs.", false], ["Reptiles are cold-blooded.", true], ["Fish breathe through gills.", true], ["Birds have fur instead of feathers.", false], ["Amphibians need water or a moist habitat.", true]],
    sentences: ["Vertebrates are animals with backbones.", "Mammals have hair or fur.", "Reptiles usually have scales.", "Amphibians can live on land and in water.", "Fish take oxygen through their gills.", "Birds have feathers and wings.", "Scientists classify animals by their features."],
    tips: ["Warm-blooded does not mean the blood feels hot.", "The plural of fish is often fish when we mean several fish of the same kind."],
  },
  u2l2: {
    title: "Language",
    strapline: "Compare the biggest, smallest, fastest and strongest animals.",
    objectives: ["Form comparative adjectives.", "Form superlative adjectives.", "Use than and the correctly."],
    definitions: [
      ["comparative", "a form used to compare two people, animals or things"], ["superlative", "a form used to compare one with a whole group"],
      ["enormous", "extremely large"], ["tiny", "extremely small"], ["strong", "having a lot of power"],
      ["fast", "moving quickly"], ["long", "measuring a great distance from end to end"], ["tall", "having a great height"],
      ["discover", "to find something for the first time"], ["natural world", "plants, animals and other things found in nature"],
    ],
    languageTitle: "Comparatives and superlatives",
    languageNotes: ["Add -er for many short adjectives: small → smaller.", "Add -est for the superlative: small → the smallest.", "Use more and most with many long adjectives. Learn irregular forms: good, better, the best."],
    readingTitle: "Big and Small in the Animal World",
    summary: "Animals come in extraordinary sizes. Elephants, blue whales, whale sharks, ostriches, hummingbirds and tiny frogs show how comparatives and superlatives help us describe the natural world.",
    keyIdeas: ["The blue whale is the biggest animal.", "An African elephant is bigger than an Asian elephant.", "An ostrich is fast but cannot fly."],
    checks: [["We use than after many comparative forms.", true], ["Bigger is the superlative form of big.", false], ["The blue whale is bigger than the whale shark.", true], ["Smallest compares only two things.", false], ["Good changes to better in the comparative.", true], ["The word tiny means very large.", false]],
    sentences: ["An African elephant is bigger than an Asian elephant.", "The blue whale is the biggest animal in the world.", "A whale shark is smaller than a blue whale.", "The hummingbird is one of the smallest birds.", "An ostrich is faster than many other birds.", "This frog is the tiniest vertebrate in the group.", "Ants are stronger than they look."],
    tips: ["Double the final consonant in big → bigger → biggest.", "Do not use more bigger; use bigger."],
  },
  u2l3: {
    title: "Invertebrates",
    strapline: "Explore the huge animal group that has no backbone.",
    objectives: ["Define invertebrate.", "Compare several invertebrate groups.", "Find facts during simple research."],
    definitions: [
      ["invertebrate", "an animal without a backbone"], ["shell", "a hard outer covering that protects an animal"],
      ["jellyfish", "a soft-bodied sea invertebrate"], ["octopus", "a sea invertebrate with eight arms"],
      ["squid", "a fast-swimming sea invertebrate with a long body"], ["snail", "a slow invertebrate that usually has a spiral shell"],
      ["insect", "an invertebrate with six legs"], ["arachnid", "an invertebrate group that includes spiders"],
      ["grasshopper", "a jumping insect with strong back legs"], ["research", "careful study to find information"],
    ],
    languageTitle: "All, some and most",
    languageNotes: ["Use all when a fact is true for every member of a group.", "Use some when it is true for part of the group.", "Use most when it is true for more than half but not all."],
    readingTitle: "An Amazing World Without Backbones",
    summary: "Most animal species are invertebrates. Some live on land and others in water. They may have hard shells or soft bodies, and they move in many different ways.",
    keyIdeas: ["More than ninety percent of animal species are invertebrates.", "Not all invertebrates have shells.", "Spiders are arachnids, not insects."],
    checks: [["Invertebrates do not have backbones.", true], ["All invertebrates can swim.", false], ["Insects have six legs.", true], ["Spiders are insects.", false], ["Some invertebrates have hard shells.", true], ["An octopus is a vertebrate.", false]],
    sentences: ["Invertebrates are animals without backbones.", "Some crabs have hard shells.", "Jellyfish have soft bodies.", "An octopus can swim very well.", "Snails usually move slowly.", "Grasshoppers are insects with six legs.", "A spider is an arachnid with eight legs."],
    tips: ["Octopus can become octopuses in normal English.", "Do not confuse insect, which has six legs, with arachnid, which has eight."],
  },
  u2l4: {
    title: "CLIL: Art",
    strapline: "Mix science and art to understand flowers and colour.",
    objectives: ["Identify primary and secondary colours.", "Explain how flowers use colour.", "Describe lighter and darker shades."],
    definitions: [
      ["primary colour", "a basic colour that cannot be made by mixing other colours"], ["secondary colour", "a colour made by mixing two primary colours"],
      ["pollen", "fine powder that flowers need to make seeds"], ["reproduce", "to make new plants or animals of the same kind"],
      ["attract", "to make something come closer"], ["shade", "a lighter or darker form of a colour"],
      ["colour wheel", "a circle that shows relationships between colours"], ["mix", "to combine two or more things"],
      ["lighter", "closer to white or less dark"], ["darker", "closer to black or less light"],
    ],
    languageTitle: "Explaining a process",
    languageNotes: ["Use by + -ing to explain how: We make orange by mixing red and yellow.", "Use because to give a reason.", "Use adding to describe an extra step."],
    readingTitle: "Why Flowers Have Bright Colours",
    summary: "Bright flowers attract insects that carry pollen. In art, red, yellow and blue are primary colours. Mixing them creates secondary colours and adding white or black changes the shade.",
    keyIdeas: ["Primary colours are red, yellow and blue.", "Red and yellow make orange.", "White makes a colour lighter and black makes it darker."],
    checks: [["Purple can be made from red and blue.", true], ["Green is a primary colour.", false], ["Bright flowers can attract insects.", true], ["Adding white makes a colour darker.", false], ["A colour wheel shows colour relationships.", true], ["Pollen helps flowers reproduce.", true]],
    sentences: ["Primary colours cannot be made by mixing other colours.", "Red and yellow make orange.", "Blue and yellow make green.", "Red and blue make purple.", "Bright flowers attract insects.", "Adding white makes a colour lighter.", "Adding black makes a colour darker."],
    tips: ["Colour is British spelling; color is American spelling.", "Use make, not do, when talking about creating a colour."],
  },
  u2l5: {
    title: "Linking Ideas",
    strapline: "Connect facts and viewpoints to create strong paragraphs.",
    objectives: ["Use linking words accurately.", "Describe how a water lily adapts.", "Present two different viewpoints."],
    definitions: [
      ["however", "a linking word that introduces a contrast"], ["in addition", "a phrase that adds more information"],
      ["on one hand", "a phrase that introduces one side of an idea"], ["on the other hand", "a phrase that introduces the opposite side"],
      ["adapt", "to change or have features that help survival"], ["surface", "the top or outside part of something"],
      ["stem", "the plant part that supports leaves and carries water"], ["root", "the plant part that takes in water and holds the plant"],
      ["seed", "the part from which a new plant can grow"], ["spread", "to cover or move across a wider area"],
    ],
    languageTitle: "However, in addition and two-sided views",
    languageNotes: ["Use however to show contrast between ideas.", "Use in addition to add another supporting fact.", "Use on one hand and on the other hand to compare two viewpoints."],
    readingTitle: "The Water Lily",
    summary: "Water lilies have broad floating leaves, long stems and roots under the water. Their features help them survive, although large groups of lilies can make life difficult for other organisms below the surface.",
    keyIdeas: ["Leaves and flowers stay near the water surface.", "Roots and much of the stem are below the water.", "Adaptations can have advantages and disadvantages."],
    checks: [["However can introduce a contrast.", true], ["In addition removes information from a paragraph.", false], ["Water lily roots spread under the water.", true], ["All of a water lily is above the water.", false], ["A long stem helps the leaf reach the surface.", true], ["Two-sided phrases can compare viewpoints.", true]],
    sentences: ["Most plants grow in soil.", "However, some plants grow in water.", "Water lilies have large floating leaves.", "In addition, they have long stems.", "Their roots spread under the water.", "On one hand, the flowers look beautiful.", "On the other hand, dense leaves can block light."],
    tips: ["Put a comma after however when it begins a sentence.", "Do not use but immediately after however in the same clause."],
  },
  u3l1: {
    title: "My Community",
    strapline: "Understand belonging, shared places and good citizenship.",
    objectives: ["Define community and neighbourhood.", "Identify examples of good citizenship.", "Use possessive words to talk about belonging."],
    definitions: [
      ["community", "people who live, work or share activities in the same area"], ["neighbourhood", "the streets and places close to a person's home"],
      ["citizenship", "responsible and helpful behaviour in a community"], ["society", "people living together in an organised group"],
      ["belong", "to be part of a group or place"], ["polite", "showing respect and good manners"],
      ["helpful", "ready to give help"], ["fair", "treating people equally and reasonably"],
      ["activity", "something people do"], ["local", "connected to the nearby area"],
    ],
    languageTitle: "Possession: my, your, mine and yours",
    languageNotes: ["Use my or your before a noun: This is my neighbourhood.", "Use mine or yours without a noun: The blue bike is mine.", "Use this for something near and that for something farther away."],
    readingTitle: "A Community Is More Than a Place",
    summary: "A community includes people, places, ideas and shared activities. Good citizens work hard, help others and behave kindly and fairly at home, school and local clubs.",
    keyIdeas: ["One person can belong to several communities.", "Communities include shared ideas and activities.", "Good citizenship supports everyone."],
    checks: [["A community can include people and shared activities.", true], ["Citizenship means ignoring other people.", false], ["Mine can stand without a noun.", true], ["A neighbourhood is always a whole country.", false], ["Helpful and fair behaviour supports a community.", true], ["People can belong to more than one community.", true]],
    sentences: ["My community includes my family and school.", "This neighbourhood is ours.", "That blue bicycle is yours.", "Good citizens help other people.", "We behave in a kind and fair way.", "A sports club can be a community.", "Local places bring people together."],
    tips: ["Do not write mine neighbourhood; write my neighbourhood.", "Neighbourhood is British spelling; neighborhood is American spelling."],
  },
  u3l2: {
    title: "The History of Egypt",
    strapline: "Travel through the great periods of ancient Egyptian history.",
    objectives: ["Sequence key events in ancient Egypt.", "Use historical vocabulary.", "Use the past simple for completed events."],
    definitions: [
      ["ancient", "from a very long time ago"], ["pharaoh", "a ruler of ancient Egypt"],
      ["dynasty", "a family of rulers over several generations"], ["unite", "to join separate parts into one"],
      ["Lower Egypt", "the northern part of ancient Egypt near the Nile Delta"], ["Upper Egypt", "the southern part of ancient Egypt along the Nile"],
      ["kingdom", "a land ruled by a king or queen"], ["control", "to have power over something"],
      ["BCE", "a label for years before the Common Era"], ["Nile", "the great river that runs through Egypt"],
    ],
    languageTitle: "Past simple for history",
    languageNotes: ["Use the past simple for finished historical events: People settled near the Nile.", "Regular verbs usually add -ed.", "Learn irregular forms such as begin → began and become → became."],
    readingTitle: "From Two Lands to One Egypt",
    summary: "People settled near the Nile thousands of years ago. Upper and Lower Egypt were once separate, then Pharaoh Mena united them. Ancient Egyptian history includes the Old, Middle and New Kingdoms.",
    keyIdeas: ["The Nile supported settlement and travel.", "Lower Egypt was in the north and Upper Egypt in the south.", "Important dynasties ruled during three major kingdoms."],
    checks: [["Lower Egypt was in the north.", true], ["Upper Egypt was beside the Mediterranean Sea.", false], ["Mena united the two parts of Egypt.", true], ["A dynasty is a family of rulers.", true], ["The New Kingdom came before the Old Kingdom.", false], ["The Nile helped Egypt become powerful.", true]],
    sentences: ["People settled near the Nile thousands of years ago.", "Lower Egypt was in the north.", "Upper Egypt was in the south.", "Pharaoh Mena united the two lands.", "Egypt controlled travel on the Nile.", "Important dynasties ruled for many years.", "The New Kingdom followed the Middle Kingdom."],
    tips: ["BCE dates move towards smaller numbers as time moves forward.", "The Nile flows north, even though Upper Egypt is in the south."],
  },
  u3l3: {
    title: "The Governorates of Egypt",
    strapline: "Read maps, compare places and talk about where people live.",
    objectives: ["Understand governorate facts.", "Use population and area vocabulary.", "Ask and answer map questions."],
    definitions: [
      ["governorate", "a main administrative area of Egypt"], ["capital", "the main city where a government is based"],
      ["population", "the number of people living in a place"], ["area", "the amount of space inside a boundary"],
      ["square kilometre", "a unit used to measure a large area"], ["map", "a drawing that shows places and locations"],
      ["border", "a line that separates two areas"], ["coast", "land beside the sea"],
      ["desert", "a very dry area with little rain"], ["region", "a particular part of a country or the world"],
    ],
    languageTitle: "How many? How big? Where?",
    languageNotes: ["Use how many for countable people or places.", "Use how big to ask about area or size.", "Use in the north, south, east or west to describe location."],
    readingTitle: "Egypt on the Map",
    summary: "Egypt is divided into twenty-seven governorates. They differ in population, area and landscape. Maps help us compare coastal, Nile Valley and desert regions.",
    keyIdeas: ["A governorate can include cities and countryside.", "Population and area describe different facts.", "Map keys and directions help us read a map."],
    checks: [["Egypt has twenty-seven governorates.", true], ["Population means the size of the land.", false], ["Square kilometres measure area.", true], ["A coast is land beside the sea.", true], ["Every governorate has the same population.", false], ["A map can show borders and directions.", true]],
    sentences: ["Egypt has twenty-seven governorates.", "A governorate can include cities and countryside.", "Cairo has a large population.", "Area is measured in square kilometres.", "The map shows important borders.", "Alexandria is on the Mediterranean coast.", "New Valley includes a large desert area."],
    tips: ["Population is a number of people; populated describes a place.", "Use kilometres for distance and square kilometres for area."],
  },
  u3l4: {
    title: "CLIL: Music",
    strapline: "Listen to the traditional sounds of different Egyptian regions.",
    objectives: ["Name traditional instruments.", "Compare regional folk music.", "Classify string, wind and percussion sounds."],
    definitions: [
      ["folk music", "traditional music passed through a community"], ["instrument", "an object used to make music"],
      ["string instrument", "an instrument that makes sound from vibrating strings"], ["wind instrument", "an instrument played by blowing air"],
      ["percussion", "instruments played by hitting or shaking"], ["oud", "a pear-shaped Middle Eastern string instrument"],
      ["ney", "a traditional flute played by blowing"], ["rhythm", "the pattern of beats in music"],
      ["clapping", "making a sound by striking the hands together"], ["drumming", "playing rhythm on a drum"],
    ],
    languageTitle: "Talking about musical traditions",
    languageNotes: ["Use from to connect music to a region.", "Use such as to give examples of instruments.", "Use includes to add parts of a musical style."],
    readingTitle: "Music Across Egypt",
    summary: "Egyptian folk music changes from one region to another. Saidi, Nubian and Bedouin traditions use different instruments, rhythms, clapping, drumming and singing.",
    keyIdeas: ["Saidi music uses string and wind instruments.", "Clapping and drumming are important in Nubian music.", "Bedouin songs often describe special events."],
    checks: [["The oud is a string instrument.", true], ["The ney is played by hitting it.", false], ["Nubian music often uses clapping and drumming.", true], ["All Egyptian folk music is exactly the same.", false], ["Rhythm is a pattern of beats.", true], ["Folk music can show regional traditions.", true]],
    sentences: ["Egypt has many styles of folk music.", "The oud is a string instrument.", "The ney is a wind instrument.", "Saidi musicians use several traditional instruments.", "Nubian music often includes clapping and drumming.", "Bedouin music includes singing.", "Rhythm helps people move together."],
    tips: ["Music is usually uncountable; say some music, not a music.", "Musician is a person; musical is an adjective."],
  },
  u3l5: {
    title: "Writing",
    strapline: "Describe Egyptian folk dancing with vivid and organised details.",
    objectives: ["Identify useful descriptive details.", "Organise a paragraph by topic.", "Write about music, movement and costume."],
    definitions: [
      ["folk dancing", "traditional dancing connected to a community"], ["lively", "full of energy and excitement"],
      ["colourful", "having many bright colours"], ["costume", "special clothing worn for a performance"],
      ["pattern", "a repeated decorative design or movement"], ["perform", "to present music, dance or drama to people"],
      ["tradition", "a custom passed from one generation to another"], ["stick", "a long thin piece of wood used in some dances"],
      ["plain", "simple and without decoration"], ["famous", "known by many people"],
    ],
    languageTitle: "A descriptive paragraph",
    languageNotes: ["Group details about music, movement and clothing.", "Use adjectives before nouns: colourful costumes.", "Use carefully chosen verbs: dancers step, turn, clap and perform."],
    readingTitle: "Folk Dancing in Egypt",
    summary: "Egyptian folk dances reflect regional music and traditions. Dancers may use rhythmic steps, sticks and special costumes. Each region adds its own instruments and performance style.",
    keyIdeas: ["Dance and folk music are closely linked.", "Costumes can be plain, patterned or brightly coloured.", "Strong verbs and adjectives make descriptions lively."],
    checks: [["A costume is special clothing for a performance.", true], ["Plain means covered in many patterns.", false], ["Folk dance can reflect regional traditions.", true], ["Descriptive writing should avoid all adjectives.", false], ["Perform is a verb.", true], ["A paragraph is clearer when related details stay together.", true]],
    sentences: ["Folk dancing has a long history in Egypt.", "Nubian dancing is lively and colourful.", "Dancers move to the rhythm of the music.", "Some performers use sticks in careful patterns.", "Special costumes may be dark or brightly coloured.", "Musicians play traditional instruments.", "A clear paragraph groups related details."],
    tips: ["Use -ly adverbs to describe actions: carefully, quickly, proudly.", "Avoid repeating nice; choose precise adjectives such as lively or colourful."],
  },
  u4l1: {
    title: "Rural and Urban Places",
    strapline: "Compare busy cities with peaceful villages and countryside.",
    objectives: ["Describe urban and rural places.", "Compare population and services.", "Speak about advantages and challenges."],
    definitions: [
      ["urban", "connected to a town or city"], ["rural", "connected to the countryside"],
      ["metropolitan", "connected to a very large city and nearby areas"], ["densely populated", "having many people in a small area"],
      ["sparsely populated", "having few people across an area"], ["inhabitant", "a person who lives in a place"],
      ["congestion", "too much traffic in one place"], ["pedestrian", "a person travelling on foot"],
      ["isolated", "far away from other places or people"], ["service", "a useful facility such as a school, shop or hospital"],
    ],
    languageTitle: "Comparing places",
    languageNotes: ["Use whereas or while to compare different places.", "Use there is for one thing and there are for more than one.", "Use much with uncountable nouns and many with countable nouns."],
    readingTitle: "Two Very Different Homes",
    summary: "A large city offers many services but can have heavy traffic and congestion. A small desert village may be peaceful and traditional but more isolated and sparsely populated.",
    keyIdeas: ["Urban areas usually have more inhabitants and services.", "Rural places may be quieter and less crowded.", "Every place has advantages and challenges."],
    checks: [["A pedestrian travels on foot.", true], ["Densely populated means very few people live there.", false], ["Congestion is common in busy traffic.", true], ["Rural always means inside a large city.", false], ["A village can be isolated.", true], ["Services include schools, shops and hospitals.", true]],
    sentences: ["Greater Cairo is a metropolitan area.", "The city is densely populated.", "Heavy traffic can cause congestion.", "Pedestrians must cross roads carefully.", "The village is sparsely populated.", "Rural families may live far from city centres.", "Both places have useful services."],
    tips: ["People is the usual plural of person.", "Traffic and congestion are uncountable nouns."],
  },
  u4l2: {
    title: "Language",
    strapline: "Build accurate regular and irregular plural nouns.",
    objectives: ["Form regular plurals.", "Recognise common irregular plurals.", "Use some, any and numbers with plural nouns."],
    definitions: [
      ["plural", "a noun form that means more than one"], ["regular plural", "a plural usually formed with -s or -es"],
      ["irregular plural", "a plural that does not follow the usual -s rule"], ["person", "one human being"],
      ["people", "the usual plural of person"], ["child", "a young person"],
      ["children", "the plural of child"], ["goose", "a large water bird"],
      ["geese", "the plural of goose"], ["sheep", "a farm animal whose singular and plural forms are the same"],
    ],
    languageTitle: "Plural noun patterns",
    languageNotes: ["Most nouns add -s: sister → sisters.", "Nouns ending in -s, -sh, -ch or -x often add -es.", "Learn irregular forms such as men, women, children, geese and people."],
    readingTitle: "Life in a Nile Village",
    summary: "A village family grows crops and keeps animals. Their description provides many regular and irregular plural nouns, including tomatoes, potatoes, sheep, buffaloes, children, women and men.",
    keyIdeas: ["Some nouns change their spelling in the plural.", "Sheep has the same singular and plural form.", "Context shows whether a noun means one or more."],
    checks: [["Children is the plural of child.", true], ["Sheeps is the correct plural of sheep.", false], ["Geese is the plural of goose.", true], ["Every plural noun ends in -s.", false], ["Women is an irregular plural.", true], ["Tomatoes ends in -es.", true]],
    sentences: ["There are six sheep in the field.", "Two buffaloes live near the farm.", "The children help their parents.", "Several women work in the village.", "Three men carry the boxes.", "Egyptian geese swim on the river.", "Farmers grow tomatoes and potatoes."],
    tips: ["Woman becomes women, with a different vowel sound.", "Do not add -s to children, people or sheep."],
  },
  u4l3: {
    title: "A Carpet Workshop",
    strapline: "Follow the skilled steps behind a traditional Egyptian carpet.",
    objectives: ["Sequence the carpet-making process.", "Use craft vocabulary.", "Connect ideas with time and contrast conjunctions."],
    definitions: [
      ["artisan", "a skilled person who makes things by hand"], ["craft", "an activity that uses skill to make something"],
      ["wool", "soft animal fibre used to make yarn"], ["spin", "to twist fibres together into thread or yarn"],
      ["dye", "a substance used to change the colour of material"], ["yarn", "long twisted fibre used for knitting or weaving"],
      ["warp", "the fixed lengthwise threads on a loom"], ["weave", "to cross threads over and under each other"],
      ["loom", "a frame or machine used for weaving"], ["synthetic", "made by chemical processes rather than from natural material"],
    ],
    languageTitle: "So that, although, before and as soon as",
    languageNotes: ["Use so that to explain purpose.", "Use although to introduce a contrast.", "Use before and as soon as to show the order and timing of actions."],
    readingTitle: "Visiting a Traditional Workshop",
    summary: "Artisans clean and spin wool, colour the yarn with dyes, make a strong warp and weave patterns on a loom. Natural and synthetic dyes create different results, and each carpet takes time and skill.",
    keyIdeas: ["Wool is cleaned before it is spun.", "Yarn must be dyed and dried before weaving.", "The warp supports the carpet pattern."],
    checks: [["An artisan is a skilled craft worker.", true], ["The warp is made after the finished carpet.", false], ["A loom is used for weaving.", true], ["Although introduces a contrast.", true], ["Yarn is dyed before the wool is cleaned.", false], ["Traditional carpets can use natural dyes.", true]],
    sentences: ["First, the artisans clean the wool.", "They spin the wool to make yarn.", "The yarn is dyed so that it has bright colour.", "Although some workshops use synthetic dyes, others use natural dyes.", "The yarn dries before the artisans weave.", "A strong warp supports the carpet.", "Every time I see the carpet, I remember the artisans' skill."],
    tips: ["Dye is the colour substance; die has a completely different meaning.", "Weave is the base form, wove is past and woven is the past participle."],
  },
  u4l4: {
    title: "CLIL: Math",
    strapline: "Solve multiplication problems hidden inside real-life stories.",
    objectives: ["Identify the numbers in a word problem.", "Choose multiplication or division.", "Write a clear answer with a unit."],
    definitions: [
      ["multiply", "to add the same number in equal groups"], ["divide", "to separate a total into equal groups"],
      ["factor", "a number multiplied by another number"], ["product", "the answer to a multiplication"],
      ["total", "the complete amount"], ["each", "every one in a group considered separately"],
      ["per", "for each"], ["estimate", "to find a close answer quickly"],
      ["operation", "a mathematical action such as adding or multiplying"], ["word problem", "a maths question written as a short situation"],
    ],
    languageTitle: "Reading mathematical problems",
    languageNotes: ["Underline the question and circle useful numbers.", "Words such as each and every often suggest equal groups.", "Write the unit after the number in the final answer."],
    readingTitle: "Numbers in Village Work",
    summary: "Farmers, weavers and families use multiplication to calculate groups of sheep, yearly carpet production and numbers of young animals. Clear reading is as important as calculation.",
    keyIdeas: ["A word problem includes a situation and a question.", "Each tells us the size of one equal group.", "An estimate helps check whether an exact answer is reasonable."],
    checks: [["The product is the answer to a multiplication.", true], ["Each usually describes unequal groups.", false], ["An estimate must always be exactly correct.", false], ["A final answer should include a unit.", true], ["Factors are numbers being multiplied.", true], ["Word problems need careful reading.", true]],
    sentences: ["Read the whole problem carefully.", "Circle the useful numbers.", "Underline what the question asks.", "Choose the correct operation.", "Multiply the number of groups by the size of each group.", "Estimate to check your calculation.", "Write the answer with the correct unit."],
    tips: ["Do not use every number if it is not needed.", "A written unit such as sheep or carpets makes the answer complete."],
  },
  u4l5: {
    title: "Writing",
    strapline: "Introduce your city, neighbourhood and favourite places.",
    objectives: ["Organise writing with headings.", "Describe a place clearly.", "Use because to explain opinions."],
    definitions: [
      ["heading", "a short title for a section of writing"], ["subheading", "a smaller title inside a larger section"],
      ["city", "a large and important urban place"], ["neighbourhood", "the area close to a person's home"],
      ["apartment", "a home that is part of a larger building"], ["industry", "businesses that make products or provide services"],
      ["port", "a place where ships load and unload"], ["garden", "an outdoor place where plants are grown"],
      ["favourite", "liked more than other choices"], ["visitor", "a person who comes to see a place"],
    ],
    languageTitle: "A three-part place description",
    languageNotes: ["Use one section for the city, one for the neighbourhood and one for your opinion.", "Use because to explain why you like a place.", "Use there is and there are to describe services and landmarks."],
    readingTitle: "My City: Alexandria",
    summary: "A young writer introduces Alexandria, describes her family neighbourhood and explains why she enjoys local services and gardens. Headings keep the information easy to follow.",
    keyIdeas: ["A heading previews the subject of a section.", "Specific place details make writing interesting.", "An opinion becomes stronger when it includes a reason."],
    checks: [["A heading helps organise a text.", true], ["Because introduces a reason.", true], ["There are is used for one singular place.", false], ["A port is connected to ships.", true], ["A place description should include no details.", false], ["A writer can separate city and neighbourhood information.", true]],
    sentences: ["I live in Alexandria.", "It is a beautiful city on the Mediterranean Sea.", "There are many useful services in my neighbourhood.", "My family lives in an apartment.", "The city has an important port.", "I enjoy the gardens because they are peaceful.", "I hope you visit my city one day."],
    tips: ["Use a capital letter for city and place names.", "Avoid starting every sentence with I; vary your sentence openings."],
  },
  u5l1: {
    title: "Natural Resources",
    strapline: "Discover the materials we receive from nature and use every day.",
    objectives: ["Define natural resource.", "Classify renewable and non-renewable resources.", "Connect resources to everyday products."],
    definitions: [
      ["natural resource", "a useful material or source that comes from nature"], ["renewable", "able to be replaced naturally in a useful time"],
      ["non-renewable", "limited and not quickly replaced after use"], ["petroleum", "a natural liquid used to make fuel and plastic"],
      ["mineral", "a natural solid substance found in the Earth"], ["metal", "a strong material such as iron, gold or silver"],
      ["soil", "the upper layer of earth where plants can grow"], ["timber", "wood prepared for building"],
      ["purpose", "the reason something is used or made"], ["replace", "to provide a new thing instead of one that is used"],
    ],
    languageTitle: "Defining and classifying",
    languageNotes: ["Use is a or are materials to define a resource.", "Use can be to describe possibility.", "Use whereas to compare renewable and non-renewable resources."],
    readingTitle: "Resources All Around Us",
    summary: "Classrooms, homes and food depend on wood, stone, metal, petroleum, water and soil. Some resources can be renewed, while others may run out and must be used carefully.",
    keyIdeas: ["Many manufactured products begin as natural resources.", "Sun, wind and flowing water are renewable.", "Metal and petroleum are non-renewable."],
    checks: [["Petroleum is a natural resource.", true], ["Renewable means a resource can never be used.", false], ["Soil supports plant growth.", true], ["Metal can be replaced immediately by nature.", false], ["Wood comes from trees.", true], ["Natural resources have many purposes.", true]],
    sentences: ["Natural resources come from nature.", "Wood is used to make furniture.", "Stone can be used to construct buildings.", "Plastic is made from petroleum.", "Plants grow in soil.", "Sunlight is a renewable resource.", "Non-renewable resources can run out."],
    tips: ["Resource is countable: one resource, many resources.", "Natural does not always mean renewable."],
  },
  u5l2: {
    title: "Language",
    strapline: "Learn how fossil fuels form and why they affect our climate.",
    objectives: ["Name common fossil fuels.", "Explain their environmental effects.", "Use cause-and-effect language."],
    definitions: [
      ["fossil fuel", "fuel formed from ancient plants and animals"], ["coal", "a hard black fossil fuel"],
      ["crude oil", "unprocessed oil taken from underground"], ["natural gas", "a gas fossil fuel used for heat and power"],
      ["oil well", "a deep hole used to bring oil from underground"], ["greenhouse gas", "a gas that traps heat in Earth's atmosphere"],
      ["global warming", "the long-term rise in Earth's average temperature"], ["climate change", "long-term changes in climate patterns"],
      ["geologist", "a scientist who studies the Earth and its materials"], ["burn", "to use fire to release heat or energy"],
    ],
    languageTitle: "Cause and effect",
    languageNotes: ["Use because to introduce a cause.", "Use so to introduce a result.", "Use leads to or causes to describe an effect."],
    readingTitle: "Fossil Fuels and Our Climate",
    summary: "Coal, crude oil and natural gas formed from ancient living things. Burning them provides energy but releases greenhouse gases that contribute to global warming and climate change.",
    keyIdeas: ["Fossil fuels are non-renewable.", "Crude oil is processed into useful products.", "Using fewer fossil fuels can reduce greenhouse gas emissions."],
    checks: [["Coal is a fossil fuel.", true], ["Fossil fuels formed in a few days.", false], ["Burning fossil fuels releases greenhouse gases.", true], ["A geologist studies the Earth.", true], ["Natural gas is renewable.", false], ["Climate change can be linked to global warming.", true]],
    sentences: ["Fossil fuels formed from ancient living things.", "Coal is a non-renewable resource.", "Crude oil comes from underground wells.", "People burn fuels to produce energy.", "Burning fuel releases greenhouse gases.", "These gases trap heat in the atmosphere.", "Using less fossil fuel can protect the climate."],
    tips: ["Fuel can be countable or uncountable depending on the meaning.", "Do not confuse whether, which offers alternatives, with weather, which describes the atmosphere."],
  },
  u5l3: {
    title: "Renewable Energy",
    strapline: "Turn sunlight, wind, waves and tides into cleaner power.",
    objectives: ["Identify four renewable energy types.", "Explain how solar panels work.", "Describe a school visit to a solar farm."],
    definitions: [
      ["solar power", "energy collected from sunlight"], ["wind power", "energy produced from moving air"],
      ["wave power", "energy produced from the movement of sea waves"], ["tidal power", "energy produced from the regular movement of tides"],
      ["solar panel", "a device that collects energy from sunlight"], ["solar farm", "a large area containing many solar panels"],
      ["electricity", "a form of energy used to power machines and lights"], ["engineer", "a person who designs or builds useful systems"],
      ["collect", "to gather things together"], ["run out", "to be completely used so none remains"],
    ],
    languageTitle: "Talking about energy and future results",
    languageNotes: ["Use comes from to name an energy source.", "Use will for a future result or prediction.", "Use so to explain why one place is suitable."],
    readingTitle: "Solar Panels in the Desert",
    summary: "A class watches a solar farm being built near the desert. Engineers explain that the area's strong sunshine makes it an excellent place to collect solar energy and produce electricity.",
    keyIdeas: ["Renewable resources do not run out quickly.", "Deserts receive strong sunshine for solar power.", "Engineers and workers build energy systems together."],
    checks: [["Solar panels collect energy from the sun.", true], ["Wind power depends on moving water.", false], ["A solar farm contains many panels.", true], ["Renewable resources always run out immediately.", false], ["Engineers can help design energy systems.", true], ["The desert can be a good place for solar power.", true]],
    sentences: ["Renewable energy comes from resources that will not quickly run out.", "Solar panels collect energy from sunlight.", "Wind turbines use moving air.", "Wave power uses the movement of sea waves.", "Tidal power uses the movement of tides.", "Workers are building a solar farm.", "The new panels will produce electricity."],
    tips: ["Electric is an adjective; electricity is a noun.", "Use energy for the general power and power for a particular source or supply."],
  },
  u5l4: {
    title: "Pronouns",
    strapline: "Choose clear pronouns so every sentence is easy to understand.",
    objectives: ["Match nouns to subject and possessive pronouns.", "Use singular and plural reference words.", "Use they and their when gender is unknown or unimportant."],
    definitions: [
      ["pronoun", "a word used instead of a noun"], ["subject pronoun", "a pronoun such as he, she or they that performs the action"],
      ["possessive determiner", "a word such as his, her or their before a noun"], ["reference", "the person or thing a pronoun points to"],
      ["he", "a subject pronoun for a boy or man"], ["she", "a subject pronoun for a girl or woman"],
      ["they", "a pronoun for plural people or for one person when gender is unknown"], ["their", "a possessive word connected to they"],
      ["both", "the two people or things together"], ["neither", "not one and not the other of two"],
    ],
    languageTitle: "He, she, they, his, her and their",
    languageNotes: ["Use he/his for a male person and she/her for a female person.", "Use they/their for plural nouns.", "They/their can also refer to one person when we do not know or need to state gender."],
    readingTitle: "Two Science Presentations",
    summary: "Two children prepare and present renewable-energy projects. Pronouns replace repeated names and show clearly who owns each part, project and presentation.",
    keyIdeas: ["A pronoun needs a clear reference.", "Both and neither refer to two.", "Their can refer to plural children or one person of unknown gender."],
    checks: [["She can replace the name of a girl.", true], ["His is normally used before a noun connected to a girl.", false], ["Their can describe something owned by several people.", true], ["Neither means both are true.", false], ["A pronoun should have a clear reference.", true], ["They can sometimes refer to one person.", true]],
    sentences: ["Lara completed her science project.", "She presented it to the class.", "Wael prepared his project carefully.", "He spoke clearly during the presentation.", "Both children practised their talks.", "Neither child forgot their notes.", "Someone raised their hand to ask a question."],
    tips: ["Her can be an object pronoun or a possessive determiner.", "Avoid repeating a name when a clear pronoun makes the sentence smoother."],
  },
  u5l5: {
    title: "Teamwork",
    strapline: "Build a positive team where every idea and person matters.",
    objectives: ["Identify strong teamwork habits.", "Discuss responsibility and respect.", "Rank and justify team values."],
    definitions: [
      ["collaborate", "to work actively with other people"], ["communicate", "to share information, ideas or feelings"],
      ["responsible", "trusted to complete duties carefully"], ["positive attitude", "a hopeful way of thinking and behaving"],
      ["solve", "to find an answer to a problem"], ["supportive", "giving help and encouragement"],
      ["flexible", "willing to change when needed"], ["reliable", "able to be trusted to do what was promised"],
      ["respect", "care for other people's ideas and feelings"], ["brainstorm", "to produce many ideas before choosing one"],
    ],
    languageTitle: "Advice for a good team",
    languageNotes: ["Use should to give helpful advice.", "Use imperatives for clear team rules: Listen carefully.", "Use instead of to suggest a better action."],
    readingTitle: "How to Be a Good Team Member",
    summary: "Successful teams communicate, collaborate, act responsibly, solve problems and stay positive. Team members listen to different ideas, complete their tasks and ask for help when needed.",
    keyIdeas: ["Good communication includes listening.", "Responsibility means completing your part.", "A positive team focuses on solutions rather than blame."],
    checks: [["Collaborate means work together.", true], ["A reliable person often forgets promises.", false], ["Respect includes listening to other ideas.", true], ["Teams should hide problems from one another.", false], ["Brainstorming creates several possible ideas.", true], ["A positive attitude can help a team succeed.", true]],
    sentences: ["Share your ideas with the team.", "Listen carefully to other members.", "Complete your part of the project.", "Ask for help when a task is difficult.", "Brainstorm several possible solutions.", "Stay calm during challenging moments.", "Show respect for every team member."],
    tips: ["Teamwork is usually uncountable.", "Advice is a noun; advise is a verb."],
  },
  u6l1: {
    title: "Transportation",
    strapline: "Travel by air, road, rail, water and even through pipes.",
    objectives: ["Classify types of transportation.", "Listen for transport details.", "Discuss how people and goods move."],
    definitions: [
      ["transportation", "the movement of people or goods from one place to another"], ["air transport", "travel using aircraft"],
      ["road transport", "travel using roads"], ["rail transport", "travel using trains and railways"],
      ["water transport", "travel using boats or ships"], ["pipeline", "a long pipe that carries water, oil or gas"],
      ["route", "the path used to travel between places"], ["cargo", "goods carried by a ship, plane or vehicle"],
      ["electric", "powered by electricity"], ["government", "the group that manages a country or region"],
    ],
    languageTitle: "Talking about transport systems",
    languageNotes: ["Use by + transport without an article: by train, by ship.", "Use on for public transport and in for most private vehicles.", "Use will to discuss future transport plans."],
    readingTitle: "Five Ways to Move",
    summary: "People and goods move by aircraft, roads, railways, waterways and pipelines. Each system has a different purpose, route and effect on communities and the environment.",
    keyIdeas: ["Pipelines can carry water to new towns.", "Rail can move many passengers or goods.", "Ancient and modern Egyptians have used boats on the Nile."],
    checks: [["A pipeline can carry water.", true], ["Rail transport uses airplanes.", false], ["Cargo means goods being carried.", true], ["Ships are part of water transport.", true], ["A route is a type of fuel.", false], ["Electric trains use electricity.", true]],
    sentences: ["People travel by air, road, rail and water.", "Pipelines carry water over long distances.", "A train follows a railway route.", "Ships carry cargo through the Suez Canal.", "Aircraft connect distant cities.", "The government will build new transport systems.", "Electric transport can reduce some pollution."],
    tips: ["Transport is common in British English; transportation is common in American English.", "Say by train but on the train."],
  },
  u6l2: {
    title: "Language",
    strapline: "Make exciting predictions about travel and life in the future.",
    objectives: ["Form positive and negative future sentences.", "Ask and answer will questions.", "Use future time expressions."],
    definitions: [
      ["prediction", "a statement about what someone thinks will happen"], ["future", "the time after the present"],
      ["will", "a modal verb used for predictions and future decisions"], ["won't", "the short form of will not"],
      ["self-driving", "able to move safely without a human driver"], ["flying taxi", "a proposed aircraft used for short passenger trips"],
      ["robot", "a machine that can perform tasks automatically"], ["solar energy", "energy that comes from sunlight"],
      ["Mars", "the fourth planet from the Sun"], ["vacation", "a period of time for rest or travel"],
    ],
    languageTitle: "Will and won't",
    languageNotes: ["Use will + base verb: People will travel.", "Use won't + base verb for negatives.", "Move will before the subject in questions: Will people live on Mars?"],
    readingTitle: "Tomorrow's Transportation",
    summary: "Future predictions imagine solar aircraft, flying taxis, robots, self-driving cars and space travel. Will helps us express these ideas even when we are not certain they will happen.",
    keyIdeas: ["The verb after will stays in the base form.", "Questions begin with will.", "Short answers repeat will or won't."],
    checks: [["Will is followed by the base verb.", true], ["Won't means will not.", true], ["We add -s to the verb after will with he.", false], ["Will people travel? is a future question.", true], ["A prediction is always a certain fact.", false], ["No, they won't is a correct short answer.", true]],
    sentences: ["People will travel in cleaner vehicles.", "Airplanes will use more renewable energy.", "Robots will not drive every train next year.", "Will people use flying taxis in the future?", "Yes, they will.", "My family won't buy a self-driving car soon.", "Perhaps humans will travel to Mars one day."],
    tips: ["Never write will to travel; write will travel.", "The contraction 'll joins to the subject: she'll, we'll, they'll."],
  },
  u6l3: {
    title: "Tech Jobs",
    strapline: "Meet the designers and engineers creating tomorrow's technology.",
    objectives: ["Understand modern technology jobs.", "Listen to a simple careers podcast.", "Discuss skills needed for future work."],
    definitions: [
      ["technology", "tools and systems created using scientific knowledge"], ["UX designer", "a person who improves how people experience a product"],
      ["VR", "virtual reality, a computer-created environment that feels immersive"], ["robotics engineer", "a person who designs or builds robots"],
      ["autonomous", "able to operate without direct human control"], ["podcast", "an audio programme available online"],
      ["search engine", "an online tool used to find information"], ["career", "a long-term path of work and learning"],
      ["skill", "an ability developed through learning and practice"], ["creative", "able to develop original and useful ideas"],
    ],
    languageTitle: "Describing jobs and skills",
    languageNotes: ["Use a or an before a singular job title.", "Use someone who to explain a job.", "Use need to + base verb to describe required skills."],
    readingTitle: "Jobs in Technology",
    summary: "Technology careers include user-experience design, virtual-reality development and robotics engineering. These jobs combine creativity, problem-solving, communication and technical knowledge.",
    keyIdeas: ["UX means user experience.", "VR can be used for learning as well as games.", "Robots can work on farms, in factories and in schools."],
    checks: [["UX stands for user experience.", true], ["VR is only used for games.", false], ["An autonomous machine can operate with less direct control.", true], ["A podcast is always a printed book.", false], ["Tech jobs can need creativity.", true], ["Robotics engineers work with robots.", true]],
    sentences: ["A UX designer improves user experiences.", "Virtual reality creates an immersive digital environment.", "A robotics engineer designs useful machines.", "Autonomous machines can perform some tasks independently.", "A podcast shares information through audio.", "Future workers will need creative skills.", "Good communication is important in technology careers."],
    tips: ["Tech is an informal short form of technology.", "Use an before autonomous because it begins with a vowel sound."],
  },
  u6l4: {
    title: "Passwords and Passphrases",
    strapline: "Protect your accounts with smart, memorable security habits.",
    objectives: ["Recognise strong and weak passwords.", "Create a safe passphrase.", "Follow clear online-safety instructions."],
    definitions: [
      ["password", "a secret set of characters used to enter an account"], ["passphrase", "a longer password made from several memorable words"],
      ["account", "a personal space or record on a digital service"], ["personal information", "private facts such as a name, birthday or address"],
      ["character", "a letter, number, space or symbol in digital text"], ["obvious", "easy to notice or guess"],
      ["secure", "protected from danger or unwanted access"], ["private", "not meant to be shared with everyone"],
      ["capital letter", "a large form of a letter such as A or B"], ["cyber safety", "safe and responsible behaviour online"],
    ],
    languageTitle: "Imperatives and sequencing",
    languageNotes: ["Use the base verb for instructions: Choose four words.", "Use don't + base verb for warnings.", "Use first, next, then and finally to order steps."],
    readingTitle: "Create a Strong Passphrase",
    summary: "Strong passwords avoid personal information, obvious words and short patterns. A memorable passphrase combines several unrelated words, spaces and capital letters and should be different for every account.",
    keyIdeas: ["Long passphrases are usually harder to guess.", "Personal information should not appear in passwords.", "Passwords must remain private."],
    checks: [["A passphrase can contain several words.", true], ["A birthday is always safe to use as a password.", false], ["Different accounts should use different passwords.", true], ["Passwords should be shared with friends.", false], ["Capital letters can make a passphrase stronger.", true], ["1234 is an obvious pattern.", true]],
    sentences: ["Choose several words that you can remember.", "Add spaces between the words.", "Use some capital letters.", "Do not include your birthday.", "Avoid easy words and number patterns.", "Use a different password for each account.", "Keep every password private."],
    tips: ["This lesson teaches safe habits, but never type a real password into a classroom activity.", "Phrase means a small group of words; passphrase combines pass and phrase."],
  },
  u6l5: {
    title: "A Fun Job",
    strapline: "Follow a container ship through the Suez Canal and meet its captain.",
    objectives: ["Understand shipping vocabulary.", "Sequence events in a short story.", "Ask and answer interview questions."],
    definitions: [
      ["container ship", "a large ship that carries goods inside metal containers"], ["captain", "the person in command of a ship"],
      ["Suez Canal", "the waterway in Egypt connecting the Mediterranean and Red Seas"], ["container", "a large strong box used to transport goods"],
      ["cargo", "goods carried by a ship"], ["straight", "not curved or bent"],
      ["windy", "having a lot of moving air"], ["interview", "a conversation in which one person asks questions"],
      ["wave", "to move a hand as a greeting"], ["transport", "to carry people or goods between places"],
    ],
    languageTitle: "Story sequence and reported facts",
    languageNotes: ["Use first, later and finally to sequence events.", "Use asked and answered when reporting a conversation.", "Use must or has to for an important job requirement."],
    readingTitle: "A Ship Captain Visits",
    summary: "Heba watches a friend's container ship pass through the Suez Canal. Later she interviews the captain and learns where the ship has travelled, what it carries and why steering a huge ship is difficult work.",
    keyIdeas: ["Container ships carry goods between countries.", "The captain must guide a very large ship carefully.", "Wind can make steering more difficult."],
    checks: [["A container ship carries goods.", true], ["The Suez Canal is a railway.", false], ["A captain is responsible for a ship.", true], ["Wind can make a ship harder to control.", true], ["An interview contains no questions.", false], ["Cargo can include toys and clothes.", true]],
    sentences: ["Heba watched the ships in the Suez Canal.", "A large container ship passed her house.", "Her family waved to the captain.", "Later, Heba prepared interview questions.", "The ship carried cargo from another country.", "A captain has to guide the ship carefully.", "Strong wind can make the job difficult."],
    tips: ["Ship can be a noun or a verb meaning send goods.", "Captain has stress on the first syllable."],
  },
};

export const projectContent: Record<string, ProjectContent> = {
  u1l6: { title: "Summer Camp Project", strapline: "Plan a healthy and creative three-day camp.", overview: "Design a camp for children aged nine and ten. Balance physical and mental activities, food, rest and fun.", usefulLanguage: ["In the morning, we will…", "This activity is important because…", "For lunch, we can have…"], steps: ["Choose a mixture of physical and mental activities.", "Plan a morning and afternoon timetable.", "Choose healthy lunches and snacks.", "Explain why your choices are good for children."], finalProduct: "A colourful three-day camp plan with short explanations." },
  u2l6: { title: "Micro-habitat Project", strapline: "Investigate the small living world near you.", overview: "Choose a small habitat and report on the vertebrates, invertebrates and plants that live there.", usefulLanguage: ["This habitat is…", "We found…", "These organisms survive because…"], steps: ["Choose a safe micro-habitat.", "Observe without disturbing living things.", "Group your findings into vertebrates, invertebrates and plants.", "Draw and label the habitat."], finalProduct: "A labelled habitat picture and a short scientific report." },
  u3l6: { title: "Tourist Guide Project", strapline: "Create a friendly guide to a special Egyptian place.", overview: "Research a place and organise information about its location, geography, attractions, history and culture.", usefulLanguage: ["It is located in…", "Visitors can…", "This place is famous for…"], steps: ["Choose a place.", "Divide research into five guide sections.", "Write short, accurate facts.", "Combine the sections into a brochure."], finalProduct: "A clear illustrated tourist brochure." },
  u4l6: { title: "Smart Growth Project", strapline: "Design a greener and friendlier city area.", overview: "Plan an area where people can walk, use public transport and reach important services easily.", usefulLanguage: ["There will be…", "People can…", "This protects the environment because…"], steps: ["Plan housing and schools.", "Add workplaces and services.", "Choose clean public transport.", "Include safe green spaces."], finalProduct: "A labelled city plan with a short description." },
  u5l6: { title: "Eco-vehicle Project", strapline: "Invent a vehicle powered by renewable energy.", overview: "Design an imaginative vehicle for personal or public transport and explain why it is eco-friendly.", usefulLanguage: ["It runs on…", "This part collects…", "It is eco-friendly because…"], steps: ["Choose the vehicle type.", "Choose at least one renewable energy source.", "Draw and label the main parts.", "Explain how the design helps the environment."], finalProduct: "A labelled eco-vehicle design and explanation." },
  u6l6: { title: "Young Entrepreneurs", strapline: "Create a simple business idea with your team.", overview: "Choose a product or service, decide who needs it and plan how it will be offered and transported.", usefulLanguage: ["Our business is called…", "We will offer…", "People need it because…"], steps: ["Choose a useful product or service.", "Name the business.", "Plan where and how you will offer it.", "Prepare a poster and practise your presentation."], finalProduct: "A simple business plan and presentation poster." },
};

export const getLessonKey = (unitId: number, lessonIndex: number) => `u${unitId}l${lessonIndex + 1}`;
